config/routes.rb
Voicev4::Application.routes.draw do

  root :to => "home#index" 

  resources :events

  resources :subscription_events

  resources :event_interests

  resources :sessions

  resources :users

  resources :interests

  resources :friendships

  resources :occasions

  resources :discussions
  
  resources :voices

  resources :surveys

  resources :survey_interests

  resources :survey_user

  resources :interest_posts

  resources :searches

  resources :messages, :except => [:show]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match 'help' => 'home#help', :as => :help

  match 'user/pending' => 'friendships#approve', :as => :user_pending_post, :via => :post
  match 'user/pending' => 'users#pending', :as => :user_pending
  match 'user/:user' => 'users#show', :as => :user_show
  match 'user/:user/connections' => 'users#connections', :as => :user_connections
  match 'user/:user/contact' =>'users#contact', :as => :user_contact
  match 'user/:user/about' => 'users#about', :as => :user_about
  match 'user/:user/interests' => 'users#interests', :as => :user_interests
  match 'user/:user/events' => 'users#events', :as => :user_events  

  match 'users' => 'users#index', :as => :users_index

  match 'interests/:interest' => 'interests#show', :as => :interest
  match 'interests/:interest/edit' => 'interests#show', :as => :interest_edit

  match 'subscribe' => 'subscriptions#create', :as => :subscribe, :via => :post
  match 'unsubscribe' => 'subscriptions#destroy', :as => :unsubscribe, :via => :post

  match "tags" => 'tags#index'
  
  match 'occasions/:occasion' => 'occasions#show', :as => :occasion
  match 'occasions/:occasion/edit' => 'occasions#show', :as => :occasion_edit
  match 'occasions/:occasion/destroy' => 'occasions#destroy', :as => :occasion_destroy

  match 'search' => 'searches#new', :as => :search
  match 'search/user_results' => 'searches#user_results', :as => :user_results
  match 'search/interest_results' => 'searches#interest_results', :as => :interest_results

  match 'recommendations' => 'recommendations#index', :as => :recommendations

  match 'surveys/:survey' => 'surveys#show', :as => :survey
  match 'committed_survey' => 'surveys#commit', :as => :committed_survey
  match 'surveys/:survey/commit' => 'survey#commit', :as => :survey_commit
  match 'show_results' => 'surveys#surveyResults', :as => :show_results

  match 'discussions/:discussion' => 'discussions#show', :as => :discussion

  match 'auth/:provider/callback', :to => 'sessions#create_with_fb'
  match 'auth/failure', :to => redirect('/')

  match 'events' => 'events#index', :as => :events_index
  match 'events/:event' => 'events#show', :as => :event
  match 'events/:event/destroy' => 'events#destroy', :as => :event_destroy
  match 'events/:event/show' => 'events#show', :as => :event_show
  match 'events/:event/edit' => 'events#edit', :as => :event_edit
  match 'events/:event/new_events' => 'events#new_events', :as => :event_new_events  
	match 'event_subscribe' => 'subscription_events#create', :as => :event_subscribe, :via => :post
  match 'event_unsubscribe' => 'subscription_events#destroy', :as => :event_unsubscribe, :via => :post

  match 'message_receiver_index' => 'users#message_receiver_index', :as => :message_receiver_index
	match 'friendships/destroy' => 'friendships#destroy', :as => :friendship_destroy, :via => :post
  match 'messages/:user' => 'messages#feed', :as => :message_feed

  match 'settings' => 'settings#index', :as => :settings

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  attr_accessible :name, :discussionposts_attributes
  has_many :discussionposts, :dependent => :destroy
  accepts_nested_attributes_for :discussionposts, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def index
    @discussions = Discussion.all
  end

  def show
    @discussion = Discussion.find(params[:id])
  end

  def new
    @discussion = Discussion.new
    1.times do
      
      discussionpost= @discussion.discussionposts.build
      discussionpost.creator_id= current_user.id
    end
  end

  def create
    @discussion = Discussion.new(params[:discussion])
    if @discussion.save
      redirect_to @discussion, :notice => "Successfully created discussion."
    else
      render :action => 'new'
    end

  end

  def edit
    @discussion = Discussion.find(params[:id])
  end

  def update
    @discussion = Discussion.find(params[:id])
    if @discussion.update_attributes(params[:discussion])
      redirect_to @discussion, :notice  => "Successfully updated discussion."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy
    redirect_to discussions_url, :notice => "Successfully destroyed discussion."
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_discussionpost_fields.html.erb
<div class="fields">
	<p>
	  <%= f.label :content, builder.creator_id %><br />
	  <%= f.text_area :content, :rows => 3 %>
	  <%= link_to_remove_fields "remove", f %>
	</p>
	
</div>

app/views/discussions/_form.html.erb
<%= form_for @discussion do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <%= f.fields_for :discussionposts do |builder| %>
    <%= render "discussionpost_fields", :f => builder %>
  <% end %>
  <p>
    <%= link_to_add_fields "Add Post", f, :discussionposts %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/discussions/edit.html.erb
<% title "Edit Discussion" %>

<%= render 'form' %>

Creator: <%= link_to "#{@creator.name} #{@creator.surname}", user_show_path(:user => discussion.creator_id)%>

<p>
  <%= link_to "Show", @discussion %> |
  <%= link_to "View All", discussions_path %>
</p>

app/views/discussions/index.html.erb
<% title "Discussions" %>
<%= link_to "New Discussion", new_discussion_path, :class=>'btn btn-primary' %>
<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for discussion in @discussions %>
    <tr>
      <td><%= discussion.name %></td>
      <td><%= link_to "Show", discussion,:class=>'btn btn-primary'%></td>
      <td><%= link_to "Edit", edit_discussion_path(discussion),:class=>'btn btn-info'%></td>
      <td><%= link_to "Destroy", discussion, :confirm => 'Are you sure?', :method => :delete,:class=>'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>

app/views/discussions/new.html.erb
<% title "New Discussion" %>

<%= render 'form' %>

<p><%= link_to "Back to List", discussions_path %></p>

app/views/discussions/show.html.erb
<% title "Discussion" %>

<p>
<strong>Name:</strong>
<%=h @discussion.name %>
</p>

<ol>
<% for selam in @discussion.discussionposts %>
<li><%=h selam.content %></li>
<%end %>
</ol>



<p>
|

  <%= link_to "Edit", edit_discussion_path(@discussion),:class=>'btn btn-info' %> |
  <%= link_to "Destroy", @discussion, :confirm => 'Are you sure?', :method => :delete ,:class=>'btn btn-danger'%> |
  <%= link_to "View All", discussions_path ,:class=>'btn btn-primary'%> |
  