config/routes.rb
Voicev4::Application.routes.draw do

  root :to => "home#index" 

  resources :events

  resources :subscription_events

  resources :event_interests

  resources :sessions

  resources :users

  resources :interests

  resources :friendships

  resources :occasions

  resources :discussions
  
  resources :voices

  resources :surveys

  resources :survey_interests

  resources :survey_user

  resources :interest_posts

  resources :searches

  resources :messages, :except => [:show]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match 'help' => 'home#help', :as => :help

  match 'user/pending' => 'friendships#approve', :as => :user_pending_post, :via => :post
  match 'user/pending' => 'users#pending', :as => :user_pending
  match 'user/:user' => 'users#show', :as => :user_show
  match 'user/:user/connections' => 'users#connections', :as => :user_connections
  match 'user/:user/contact' =>'users#contact', :as => :user_contact
  match 'user/:user/about' => 'users#about', :as => :user_about
  match 'user/:user/interests' => 'users#interests', :as => :user_interests
  match 'user/:user/events' => 'users#events', :as => :user_events  

  match 'users' => 'users#index', :as => :users_index

  match 'interests/:interest' => 'interests#show', :as => :interest
  match 'interests/:interest/edit' => 'interests#show', :as => :interest_edit

  match 'subscribe' => 'subscriptions#create', :as => :subscribe, :via => :post
  match 'unsubscribe' => 'subscriptions#destroy', :as => :unsubscribe, :via => :post

  match "tags" => 'tags#index'
  
  match 'occasions/:occasion' => 'occasions#show', :as => :occasion
  match 'occasions/:occasion/edit' => 'occasions#show', :as => :occasion_edit
  match 'occasions/:occasion/destroy' => 'occasions#destroy', :as => :occasion_destroy

  match 'search' => 'searches#new', :as => :search
  match 'search/user_results' => 'searches#user_results', :as => :user_results
  match 'search/interest_results' => 'searches#interest_results', :as => :interest_results

  match 'recommendations' => 'recommendations#index', :as => :recommendations

  match 'surveys/:survey' => 'surveys#show', :as => :survey
  match 'committed_survey' => 'surveys#commit', :as => :committed_survey
  match 'surveys/:survey/commit' => 'survey#commit', :as => :survey_commit
  match 'show_results' => 'surveys#surveyResults', :as => :show_results

  match 'discussions/:discussion' => 'discussions#show', :as => :discussion

  match 'auth/:provider/callback', :to => 'sessions#create_with_fb'
  match 'auth/failure', :to => redirect('/')

  match 'events' => 'events#index', :as => :events_index
  match 'events/:event' => 'events#show', :as => :event
  match 'events/:event/destroy' => 'events#destroy', :as => :event_destroy
  match 'events/:event/show' => 'events#show', :as => :event_show
  match 'events/:event/edit' => 'events#edit', :as => :event_edit
  match 'events/:event/new_events' => 'events#new_events', :as => :event_new_events  
	match 'event_subscribe' => 'subscription_events#create', :as => :event_subscribe, :via => :post
  match 'event_unsubscribe' => 'subscription_events#destroy', :as => :event_unsubscribe, :via => :post

  match 'message_receiver_index' => 'users#message_receiver_index', :as => :message_receiver_index
	match 'friendships/destroy' => 'friendships#destroy', :as => :friendship_destroy, :via => :post
  match 'messages/:user' => 'messages#feed', :as => :message_feed

  match 'settings' => 'settings#index', :as => :settings

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if logged_in?
  		@activities = UserActivity.where(:user_id => [current_user.friends.collect(&:id)]+ [current_user.id] ).order("created_at DESC")
      @user = current_user
      
      @tempevents = Array.new
      @tempinterests = @user.interests
      @tempinterests.each do |i|
        if i.events.count > 0 
          #@tempevents = @tempevents + i.events
          i.events.each do |e|
            unless @user.events.include?(e) 
              unless @tempevents.include?(e)
                @tempevents.push(e)
              end
            end
          end
        end
      end
      @newevents = @tempevents.last(5)

      @occasions = Occasion.last(5)
      @interests = Interest.last(5)
      @events = Event.last(5)
      @surveys = Survey.last(5)
      #@discussions = Discussion.last(5)
      @users = User.last(5)  
    end
  end

  def help
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/help.html.erb
<h2>Contact Us</h2>

<blockquote>
<p>
	Feel free to send an e-mail to
	<a href="mailto:voice.developers@gmail.com">voice.developers@gmail.com</a>
	for any of your questions related to how to use the website, 
	any abuse or inappropriate content you want to report and any feedback that
	could be useful for us to improve the application. You can be sure that your e-mails will be read and answered immediately.
</p>
<small>
	Voice Team
</small>
</blockquote>

app/views/home/index.html.erb
<% if logged_in? %>
	<div class="row">
        <div class="span6">
          <h2>Activity Feed</h2>
          	<!-- RAISE YOUR VOICE INPUT FIELD -->
            <form class="form-inline">
              <div class="input-append">
                <input class="span4" id="appendedInputButton" size="16" type="text" placeholder="Raise Your Voice!"><button class="btn" type="button">Go!</button>
              </div>
            </form>
            <% @activities.each do |activity| %>
              <% if activity.klass.constantize.where(:id=> activity.klass_id).present?%>
                <% activity_user = activity.user %>
                  <div class="row"  id="activity_feed_item">
                      <div class="span1" align="center">
                          <%= link_to image_tag("http://graph.facebook.com/#{activity_user.uid}/picture?type=square", :class => "img-circle"), user_show_path(:user => activity_user.id) %>
                      </div>
                      <div class="span5">
                            <%= link_to "#{activity_user.name} #{activity_user.surname}" , user_show_path(:user => activity_user.id) %> 
                            <% if activity.klass.constantize.column_names.include?("title") %>
                              <%= activity.action %> <%= link_to "#{activity.klass.constantize.find(activity.klass_id).title}", activity.klass.constantize.find(activity.klass_id).get_show_url %> 
                            <% elsif activity.klass == "User" %>
                              <% user = User.find(activity.klass_id) %>
                              <%= activity.action %> <%= link_to "#{user.name} #{user.surname}", User.find(user.id).get_show_url %>
                            <% elsif activity.klass.constantize.column_names.include?("name") %>
                              <%= activity.action %> <%= link_to "#{activity.klass.constantize.find(activity.klass_id).name}", activity.klass.constantize.find(activity.klass_id).get_show_url %> 
                            <% end %>
                          <p class="muted"><small><%= time_ago_in_words(activity.created_at) %> ago</small></p>
                      </div>
                  </div>
                  <hr class="bs-docs-separator">
              <% end %>
            <% end %>
        </div>
        <div class="span3">
          <div class="well">
            <!-- <div clas="well"> -->
              <h2><%= link_to "Interests", interests_path %></h2>
              <ul>
                <% @interests.each do |interest| %>
                  <li> <%= link_to "#{interest.name}", interest_path(:interest => interest.id) %></li>
                <% end %>
            </ul>
            <!-- </div> -->
          </div>
          <div class="well">
            <h2><%= link_to "Occasions", occasions_path %></h2>
            <ul>
                <% @occasions.each do |occasion| %>
                  <li> <%= link_to "#{occasion.name}", occasion_path(:occasion => occasion.id) %></li>
                <% end %>
            </ul>
          </div>
          <div class="well">
            <h2><%= link_to "Surveys", surveys_path %></h2>
            <ul>
                <% @surveys.each do |survey| %>
                  <li> <%= link_to "#{survey.name}", survey_path(:survey => survey.id) %></li>
                <% end %>
            </ul>
          </div>
         </div>

        <div class="span3">
          <div class="well">
            <h2><%= link_to "Events", events_path %></h2>
            <ul>
                <% @newevents.each do |event| %>
                  <li> <%= link_to "#{event.title}", event_path(:event => event.id) %></li>
                <% end %>
            </ul>
          </div>

          <div class="well">
            <h2><%= link_to "Users", users_path %></h2>
            <ul>
                <% @users.each do |user| %>
                  <li> <%= link_to "#{user.name} #{user.surname}", user_show_path(:user => user.id) %></li>
                <% end %>
            </ul>
          </div>
          <!-- RECOMMENDATIONS GO HERE -->
          <!-- <div class="well">
            <h2>Recommendations</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p>
          </div> -->
       </div>
      </div>
<% else %>
	<div class="center hero-unit">
		<h1>Welcome to Voice.</h1>
		<h2>
			This is the home page for the
			<a href="http://voice.com/">Voice Community</a>
			.
	    </h2>
	    <%= link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary" %>
       <%= link_to "Sign in with Facebook", "auth/facebook", :id => "sign_in" %>
	  </div>
<% end %>