config/routes.rb
Voicev4::Application.routes.draw do

  root :to => "home#index" 

  resources :events

  resources :subscription_events

  resources :event_interests

  resources :sessions

  resources :users

  resources :interests

  resources :friendships

  resources :occasions

  resources :discussions
  
  resources :voices

  resources :surveys

  resources :survey_interests

  resources :survey_user

  resources :interest_posts

  resources :searches

  resources :messages, :except => [:show]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match 'help' => 'home#help', :as => :help

  match 'user/pending' => 'friendships#approve', :as => :user_pending_post, :via => :post
  match 'user/pending' => 'users#pending', :as => :user_pending
  match 'user/:user' => 'users#show', :as => :user_show
  match 'user/:user/connections' => 'users#connections', :as => :user_connections
  match 'user/:user/contact' =>'users#contact', :as => :user_contact
  match 'user/:user/about' => 'users#about', :as => :user_about
  match 'user/:user/interests' => 'users#interests', :as => :user_interests
  match 'user/:user/events' => 'users#events', :as => :user_events  

  match 'users' => 'users#index', :as => :users_index

  match 'interests/:interest' => 'interests#show', :as => :interest
  match 'interests/:interest/edit' => 'interests#show', :as => :interest_edit

  match 'subscribe' => 'subscriptions#create', :as => :subscribe, :via => :post
  match 'unsubscribe' => 'subscriptions#destroy', :as => :unsubscribe, :via => :post

  match "tags" => 'tags#index'
  
  match 'occasions/:occasion' => 'occasions#show', :as => :occasion
  match 'occasions/:occasion/edit' => 'occasions#show', :as => :occasion_edit
  match 'occasions/:occasion/destroy' => 'occasions#destroy', :as => :occasion_destroy

  match 'search' => 'searches#new', :as => :search
  match 'search/user_results' => 'searches#user_results', :as => :user_results
  match 'search/interest_results' => 'searches#interest_results', :as => :interest_results

  match 'recommendations' => 'recommendations#index', :as => :recommendations

  match 'surveys/:survey' => 'surveys#show', :as => :survey
  match 'committed_survey' => 'surveys#commit', :as => :committed_survey
  match 'surveys/:survey/commit' => 'survey#commit', :as => :survey_commit
  match 'show_results' => 'surveys#surveyResults', :as => :show_results

  match 'discussions/:discussion' => 'discussions#show', :as => :discussion

  match 'auth/:provider/callback', :to => 'sessions#create_with_fb'
  match 'auth/failure', :to => redirect('/')

  match 'events' => 'events#index', :as => :events_index
  match 'events/:event' => 'events#show', :as => :event
  match 'events/:event/destroy' => 'events#destroy', :as => :event_destroy
  match 'events/:event/show' => 'events#show', :as => :event_show
  match 'events/:event/edit' => 'events#edit', :as => :event_edit
  match 'events/:event/new_events' => 'events#new_events', :as => :event_new_events  
	match 'event_subscribe' => 'subscription_events#create', :as => :event_subscribe, :via => :post
  match 'event_unsubscribe' => 'subscription_events#destroy', :as => :event_unsubscribe, :via => :post

  match 'message_receiver_index' => 'users#message_receiver_index', :as => :message_receiver_index
	match 'friendships/destroy' => 'friendships#destroy', :as => :friendship_destroy, :via => :post
  match 'messages/:user' => 'messages#feed', :as => :message_feed

  match 'settings' => 'settings#index', :as => :settings

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :questions_attributes, :answers_attributes, :start_time, :finish_time, :interest_tokens, :creator_id
  has_many :questions, :dependent => :destroy
  validates :name, :presence => true 
  validates :start_time, :presence => true
  validates :finish_time,  :presence => true
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  has_many :survey_interests, :foreign_key => "survey_id", :dependent => :destroy
  has_many :interests, :through => :survey_interests, :source => :interest

  has_many :survey_users, :dependent => :destroy, :foreign_key => 'surveyId'

  attr_reader :interest_tokens
	
	def interest_tokens=(tokens)
  		self.interest_ids = Interest.ids_from_tokens(tokens)
  end

  def get_show_url
    Rails.application.routes.url_helpers.survey_path(self.id)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
    @activeSurveys = Survey.where('finish_time > ?', Date.today).order('created_at DESC') 
    @finishedSurveys = Survey.where('finish_time < ?', Date.today)
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
     @survey = Survey.new
      1.times do
        question = @survey.questions.build
        1.times { question.answers.build }
    end
  end

  def create
    @survey = Survey.new(params[:survey])
    @survey.creator_id = current_user.id;
    if @survey.save
      redirect_to @survey, :notice => "Successfully created survey."
    else
      render :action => 'new'
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update

    @survey = Survey.find(params[:id])
    if @survey.update_attributes(params[:survey])
      redirect_to @survey, :notice  => "Successfully updated survey."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_url, :notice => "Successfully destroyed survey."
  end

  def commit
    params['results'].each do |key, value|
      a = Answer.find(key.to_i)
      a.count ||= 0
      a.count += 1
      a.save
    end
    s = SurveyUser.new
    s.userId = current_user.id
    s.surveyId = params['survey_id']

    if s.save   
      redirect_to surveys_path, :notice  => "Successfully submitted Your Survey Answers."
    else
      redirect_to surveys_path :notice => "Sorry! Error happened when submitting your survey answer. Please 
                                          try again or contact the Voice Developers"
    end
  end



end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_answer_fields.html.erb
<p class="fields">
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/surveys/_form.html.erb
<%= form_for @survey do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time %>
  </p>
  <p>
    <%= f.label :finish_time %><br />
    <%= f.text_field :finish_time%>
  </p>

  <div class="control-group">
      <%= f.label :target_audiance_interest, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :interest_tokens, :data => {:load => @survey.interests} %>
      </div>
  </div>
  <%= f.fields_for :questions do |builder| %>
    <%= render "question_fields", :f => builder %>
  <% end %>
  <p>
    <%= link_to_add_fields "Add Question", f, :questions %>
  </p>
  <p>
    <%= f.submit "Submit" ,:class=>'btn btn-primary'%>
  </p>
<% end %>

app/views/surveys/_question_fields.html.erb
<div class="fields">
	<p>
	  <%= f.label :content, "Question" %><br />
	  <%= f.text_area :content, :rows => 3 %>
	  <%= link_to_remove_fields "remove", f %>
	</p>
	<%= f.fields_for :answers do |builder| %>
	  <%= render 'answer_fields', :f => builder %>
	<% end %>
	<p>
		<%= link_to_add_fields "Add Answer", f, :answers %>
	</p>
</div>

app/views/surveys/_surveyResults.html.erb
<div class="tab-pane " id="finishedSurveys">
        <div class="row">
          <div class="span10">
            <table class="table table-hover">
              <caption></caption>

              <tbody>
                <% @finishedSurveys.each do |survey| %>
                <strong>
                <h3>Survey Name: <%= survey.name%></h3></br>
                </strong>
                <% survey.questions.each do |q| %>
                      <strong>
                      Question: <%= q.content %> <br>
                      </strong>
                      <% q.answers.each do |a| %>

                      <span class="badge badge-inverse">
                        <%= a.count %>
                        </span>
                        
                        <blockquote>
                        <%= a.content %> 
                  
                        <div class="progress progress-info">
                          <div class="bar" style="width: <%= a.count %>%"></div>
                        </div>
                        </blockquote>
                      <% end %>
                      <br>
                    <% end %>

                      <!-- <td><%= link_to "Show Results", show_results_path , :surveyId => survey.id,:class=>'btn btn-primary'%></td>-->
                 </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
    </div>

app/views/surveys/edit.html.erb
<% title "Edit Survey" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @survey %> |
  <%= link_to "View All", surveys_path %>
</p>

app/views/surveys/index.html.erb
<% title "Surveys" %>
<%= link_to "New Survey", new_survey_path, :class=>'btn btn-primary' %>

<p></p>

<div class="tabbable">
<ul class="nav nav-tabs" id="myTab">
 <li class="active"><a href="#activeSurveys" data-toggle="tab">Active Surveys</a></li>
 <li><a href="#finishedSurveys" data-toggle="tab">Finished Surveys</a></li>
</ul>


 <div class="tab-content">
    <div class="tab-pane in active" id="activeSurveys">
        <div class="row">
          <div class="span12">
            <table class="table table-hover">
              <caption></caption>
              <thead>
                <tr>
                  <th>Name</th>
                </tr>
              </thead>
              <tbody>
                <% @activeSurveys.each do |survey| %>
                  <tr>
                     <td><%= survey.name %></td>
                      <td><%= link_to "Show", survey,:class=>'btn btn-primary'%></td>
                 </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
    </div>
    <div class="tab-pane " id="finishedSurveys">
        <div class="row">
          <div class="span10">
            <table class="table table-hover">
              <caption></caption>
              <thead>
                <tr>
                  <th>Name</th>
                </tr>
              </thead>
              <tbody>
                <% @finishedSurveys.each do |survey| %>
                <tr>
                     <td><%= survey.name %></td>
                      <td><%= link_to "Show Results", show_results_path(:survey => survey.id) , :class=>'btn btn-primary'%></td>
                 </tr>        
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
  </div>
</ul>

app/views/surveys/new.html.erb
<% title "New Survey" %>

<%= render 'form' %>

<p>
	<%= link_to "Back to List", surveys_path %>
</p>

app/views/surveys/show.html.erb
<% @survey.name %> <br>

<% if SurveyUser.where(:userId=> current_user.id, :surveyId=>@survey.id).exists? %>
<div class="alert alert-block">
	<strong>
	  Oops! You already answered this survey!
	</strong>
</div>
<%else %>
	<%= form_for(:results, :url => committed_survey_path) do |f| %>
		<%= hidden_field_tag 'survey_id', params[:id]  %>
		<% @survey.questions.each do |q| %>
			<strong>
			<p class="lead">
			Question: <%= q.content %> <br>
			</strong>
			</p>
			<% q.answers.each do |a| %>
				
				<blockquote>
					<%= f.check_box "#{a.id}" %> <%= a.content %>
				</blockquote>
			<% end %>
			<br>
		<% end %>
		<%= f.submit "Submit" ,:class=>'btn btn-primary'%>
	<% end %>
<% end %>

<p>
	<%= link_to "Back to List", surveys_path %>
</p>

app/views/surveys/surveyResults.html.erb
<% @survey = Survey.find(params[:survey])%>


<div class="tab-pane " id="finishedSurveys">
        <div class="row">
          <div class="span10">
            <table class="table table-hover">
              <caption></caption>

             
                <strong>
                <h3>Survey Name: <%= @survey.name%></h3></br>
              
                </strong>
                <% @survey.questions.each do |q| %>
                      <strong>
                      <h4>Question: <%= q.content %></h4> <br>
                      </strong>
                      <% q.answers.each do |a| %>

                        <blockquote>                 
                          <%= a.content %>                   
                          <div class="progress progress-info">
                            <div class="bar" style="width: <%= a.count %>%"></div>
                             <span class="badge badge-inverse">
                          <%= a.count %>
                          </span>  
                          </div>

                        </blockquote>
                       
                      <% end %>
                      <br>

                    
                      
                 </tr>
                <% end %>
              
            </table>
          </div>
        </div>
    </div>

    <p>
        <%= link_to "Back to List", surveys_path %>
    </p>