config/routes.rb
Voicev4::Application.routes.draw do

  root :to => "home#index" 

  resources :events

  resources :subscription_events

  resources :event_interests

  resources :sessions

  resources :users

  resources :interests

  resources :friendships

  resources :occasions

  resources :discussions
  
  resources :voices

  resources :surveys

  resources :survey_interests

  resources :survey_user

  resources :interest_posts

  resources :searches

  resources :messages, :except => [:show]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match 'help' => 'home#help', :as => :help

  match 'user/pending' => 'friendships#approve', :as => :user_pending_post, :via => :post
  match 'user/pending' => 'users#pending', :as => :user_pending
  match 'user/:user' => 'users#show', :as => :user_show
  match 'user/:user/connections' => 'users#connections', :as => :user_connections
  match 'user/:user/contact' =>'users#contact', :as => :user_contact
  match 'user/:user/about' => 'users#about', :as => :user_about
  match 'user/:user/interests' => 'users#interests', :as => :user_interests
  match 'user/:user/events' => 'users#events', :as => :user_events  

  match 'users' => 'users#index', :as => :users_index

  match 'interests/:interest' => 'interests#show', :as => :interest
  match 'interests/:interest/edit' => 'interests#show', :as => :interest_edit

  match 'subscribe' => 'subscriptions#create', :as => :subscribe, :via => :post
  match 'unsubscribe' => 'subscriptions#destroy', :as => :unsubscribe, :via => :post

  match "tags" => 'tags#index'
  
  match 'occasions/:occasion' => 'occasions#show', :as => :occasion
  match 'occasions/:occasion/edit' => 'occasions#show', :as => :occasion_edit
  match 'occasions/:occasion/destroy' => 'occasions#destroy', :as => :occasion_destroy

  match 'search' => 'searches#new', :as => :search
  match 'search/user_results' => 'searches#user_results', :as => :user_results
  match 'search/interest_results' => 'searches#interest_results', :as => :interest_results

  match 'recommendations' => 'recommendations#index', :as => :recommendations

  match 'surveys/:survey' => 'surveys#show', :as => :survey
  match 'committed_survey' => 'surveys#commit', :as => :committed_survey
  match 'surveys/:survey/commit' => 'survey#commit', :as => :survey_commit
  match 'show_results' => 'surveys#surveyResults', :as => :show_results

  match 'discussions/:discussion' => 'discussions#show', :as => :discussion

  match 'auth/:provider/callback', :to => 'sessions#create_with_fb'
  match 'auth/failure', :to => redirect('/')

  match 'events' => 'events#index', :as => :events_index
  match 'events/:event' => 'events#show', :as => :event
  match 'events/:event/destroy' => 'events#destroy', :as => :event_destroy
  match 'events/:event/show' => 'events#show', :as => :event_show
  match 'events/:event/edit' => 'events#edit', :as => :event_edit
  match 'events/:event/new_events' => 'events#new_events', :as => :event_new_events  
	match 'event_subscribe' => 'subscription_events#create', :as => :event_subscribe, :via => :post
  match 'event_unsubscribe' => 'subscription_events#destroy', :as => :event_unsubscribe, :via => :post

  match 'message_receiver_index' => 'users#message_receiver_index', :as => :message_receiver_index
	match 'friendships/destroy' => 'friendships#destroy', :as => :friendship_destroy, :via => :post
  match 'messages/:user' => 'messages#feed', :as => :message_feed

  match 'settings' => 'settings#index', :as => :settings

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  attr_accessible :creator_id, :description, :in_trash, :name, :time

  	def get_show_url
  		Rails.application.routes.url_helpers.occasion_path(self.id)
  	end
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  def index
  	@upcomingoccasions = Occasion.where('time > ?', Date.today - 1.days).order('created_at DESC') #gecmis occasion degil ise
    @missedoccasions = Occasion.where('time < ?', Date.today - 1.days) #gecmis ise
  end

  def new
  	@occasion = Occasion.new
  end

  def create
    @occasion = Occasion.new
    #parse the time string (hh:mm)
    if (params[:day] == "today")
      @occasion.time = (Date.today + params[:occasion][:time][0..1].to_i.hour + params[:occasion][:time][3..4].to_i.minute)
    else
      @occasion.time = (Date.tomorrow + params[:occasion][:time][0..1].to_i.hour + params[:occasion][:time][3..4].to_i.minute)
    end

    if (@occasion.time > DateTime.now)
      @occasion.name = params[:occasion][:name]
      @occasion.description = params[:occasion][:description]
      @occasion.in_trash = false
      @occasion.creator_id = current_user.id
      if @occasion.save
        redirect_to occasions_url, :notice => "Successfully created occasion."
      else
        render :action => 'new'
      end
    else
      redirect_to new_occasion_url, :notice => "Please enter a valid time."
    end
  end

  def update
    @occasion = Occasion.find(params[:id])
    if @occasion.update_attributes(params[:occasion])
      redirect_to occasion_path(:occasion => @occasion.id), :notice => "Occasion has been updated."
    else
      render :action => 'edit'
    end
  end

  def destroy
    Occasion.find(params[:occasion]).destroy
    redirect_to occasions_url, :notice => "Successfully destroyed occasion."
  end

  def missed
    @occasions = Occasion.where('time < ?', Date.today - 1.days) #gecmis ise   
  end

  def show
    @occasion = Occasion.find(params[:id])
  end

  def edit
    @occasion = Occasion.find(params[:id])
  end
  

end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<%= form_for @occasion, :html => { :class => "form-horizontal"} do |f| %>
  <div class="control-group">
      <%= f.label :name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
  </div>
  <div class="control-group">
      <%= f.label :description, :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :description, :rows => 3 %>
      </div>
  </div>

<div class="control-group">
  <%= f.label :day, :class => "control-label" %>
  <div class="controls">
   <%= select_tag :day, options_for_select([["Today", "today"], ["Tomorrow", "tomorrow"]]) %>
  </div>
</div>

<div class="control-group">
  <%= f.label "Time",  :class => "control-label" %>
  <div class="controls">
    <div class="input-append bootstrap-timepicker-component">
      <%= f.text_field :time, :class => "timepicker-default input-small"%>
      <span class="add-on">
        <i class="icon-time"></i>
      </span>
    </div>
  </div>
</div>
  <div class="control-group">   
    <div class="controls">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/occasions/create.html.erb
<h1>Occasions#create</h1>
<p>Find me in app/views/occasions/create.html.erb</p>

app/views/occasions/destroy.html.erb
<h1>Occasions#destroy</h1>
<p>Find me in app/views/occasions/destroy.html.erb</p>

app/views/occasions/edit.html.erb
<h2>Edit Occasion</h2>

<%= render 'form' %>

app/views/occasions/index.html.erb
<%= link_to "Create an Occasion", new_occasion_path, :class=>'btn btn-primary' %>

<p></p>
<div class="tabbable">
<ul class="nav nav-tabs" id="myTab">
 <li class="active"><a href="#upcomingOccasions" data-toggle="tab">Upcoming Occasions</a></li>
 <li><a href="#missedOccasions" data-toggle="tab">Missed Occasions</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane in active" id="upcomingOccasions">
        <div class="row">
          <div class="span10">
            <table class="table table-hover">
              <caption></caption>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                <% @upcomingoccasions.each do |occasion| %>
                  <tr>
                    <!-- Occasion.where('created_at > ?', 1.hour.ago).count -->
                      <td>
                        <% if occasion.created_at > 1.hour.ago %>
                        <span class="label label-warning">NEW!</span>
                        <% end %>
                        <%= link_to "#{occasion.name}", occasion_path(:occasion => occasion.id) %>
                      </td>
                      <td><%= occasion.description %></td>
                      <td><%= occasion.time %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
    </div>
    <div class="tab-pane " id="missedOccasions">
        <div class="row">
          <div class="span10">
            <table class="table table-hover">
              <caption></caption>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                <% @missedoccasions.each do |occasion| %>
                  <tr>
                      <td>
                        <%= link_to "#{occasion.name}", occasion_path(:occasion => occasion.id) %>
                      </td>
                      <td><%= occasion.description %></td>
                      <td><%= occasion.time %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>

app/views/occasions/new.html.erb
<h2>New Occasion</h2>

<%= render 'form' %>

app/views/occasions/show.html.erb
<div class="row">
	<h2><%= link_to "#{@occasion.name}", occasion_path(:occasion => @occasion.id) %></h2>
	<dl ><!--class="dl-horizontal"-->
              <dt><h4>Description:</h4></dt>
              <dd><%= @occasion.description %></dd>
              <dt><h4>Date:</h4></dt>
              <dd><%= @occasion.time.strftime("%d/%m/%Y") %></dd>  
              <dt><h4>Time:</h4></dt>
              <dd><%= @occasion.time.strftime("%H:%M") %></dd>      
  </dl>
  <% if @occasion.creator_id == current_user.id %>
        <%= link_to "Edit", occasion_edit_path(:occasion => @occasion.id), :class=> 'btn btn-mini' %>
        <%= link_to "Delete", occasion_destroy_path(:occasion => @occasion.id), :class=> 'btn btn-danger btn-mini' %>
  <% end %>
  <p><%= link_to 'See other occasions', occasions_path%></p>
</div>